# Generated by Django 5.0.2 on 2024-04-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('head_quaters', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('salary', models.FloatField()),
                ('date_of_joining', models.DateField()),
                ('is_active', models.BooleanField()),
                ('shift_timing', models.CharField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apis.department')),
            ],
        ),
    ]
